### ISSUE TITLE
Travis 'sourceline' key missing, can not find packaged ZMQ prerequisites

### ISSUE THREAD

**Issue by jimklimov** [zeromq/zproject#1188]
Looking at research like https://github.com/travis-ci/travis-ci/issues/9693 I was too eager to build modular repository-source configs in generated `.travis.yml` files, along the lines of:

````
pkg_src_zeromq_ubuntu16: &pkg_src_zeromq_ubuntu16
- sourceline: 'deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_16.04/ ./'
  key_url: 'http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_16.04/Release.key'

- env: BLAH=blah
    addons:
      apt:
        sources:
        - *pkg_src_zeromq_ubuntu14
        - ubuntu-toolchain-r-test
        packages:
        - *pkg_deps_common
        - valgrind
...
````

While expansion like `- *pkg_deps_common` works for a simple list of package names in travis, it fails for a more complex object of `sources`. According to that issue linked above, `sources: \n - *pkg_src_zeromq_ubuntu14` fails while `sources: *pkg_src_zeromq_ubuntu14` on the same line is good.

Gotta find out another way of writing such things compactly to use different sets of package sources for different test cases in the matrix... Maybe this pattern would work:
````
apt:
  sources: *pkg_src_zeromq_ubuntu14
  - ubuntu-toolchain-r-test 
````

or a definition of helper object somehow, to reference it always once: `sources: *helperlist` ...
